# Global settings (imported into simulation)

NUM_PEPTIDES = 10000
HYDROPHOBIC_N_MARGIN = 2
PARTIAL_INSERTION_PROB = 0.25
MISFITTED_INSERTION_PROB = 0.5
INIT_MODE = "default"
GLYCINE_FRACTION = 0.01
ENANTIOMERIC_EXCESS = 0.5
INITIAL_MEMBRANE_THICKNESS = 12
MAX_MEMBRANE_THICKNESS = 23
VESICLE_DIAMETER = 100
MAX_PEPTIDE_LENGTH = 120
CYTOPLASM_CAPACITY = float('inf')
MAX_PEPTIDES_PER_AREA = 0.5

